// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://regnbhyxkfpeojnhltkj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJlZ25iaHl4a2ZwZW9qbmhsdGtqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU0NjQ2NDcsImV4cCI6MjA3MTA0MDY0N30.3Eh2JoWCA0QtbzBFo5oNtoDvFJ4Xiq0rs6BnHXT-VFM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});